/* GCCE (Global Clock Controller East) driver
 */
#ifndef __GCCE_QDF2400_H_INCLUDE__
#define __GCCE_QDF2400_H_INCLUDE__
#include <asm/plat-centriq/gcce.h>

/* Accepts the clock outputs from pad east_xo, generates east side
 * devices' clocks and resets. It also generates source clocks for
 * PCIe_CC, and source reset for the east side devices.
 */
#ifndef GCCE_BASE
#define GCCE_BASE			ULL(0x0FF22400000)
#endif

#define GCCE_PLL_BASE			GCCE_REG(0x00000)

/* East PLLs */
#define GCCE_EAST_PLL0			2
#define GCCE_EAST_PLL1			3

#define GCCE_CC_BASE			GCCE_REG(0x20000)

/* XO */
#define GCCE_XO				0
#define GCCE_XO_CMD_RCGR		GCCE_CC_REG(GCCE_XO, 0x0000)
#define GCCE_XO_CFG_RCGR		GCCE_CC_REG(GCCE_XO, 0x0004)
#define GCCE_AHB_CBCR			GCCE_CC_REG(GCCE_XO, 0x0008)
#define GCCE_XO_CBCR			GCCE_CC_REG(GCCE_XO, 0x000C)
#define GCCE_XO_DIV4_CBCR		GCCE_CC_REG(GCCE_XO, 0x0028)
#define GCCE_IM_SLEEP_CBCR		GCCE_CC_REG(GCCE_XO, 0x0030)

/* HMSS */
#define GCCE_HMSS			1
#define GCCE_HMSS_BUS_CMD_RCGR		GCCE_CC_REG(GCCE_HMSS, 0x0000)
#define GCCE_HMSS_NE_AHB_CBCR		GCCE_CC_REG(GCCE_HMSS, 0x001C)
#define GCCE_HMSS_SE_AHB_CBCR		GCCE_CC_REG(GCCE_HMSS, 0x0020)

/* NCSFPB (N_CONF_SFPB) */
#define GCCE_NCSFPB			2
#define GCCE_N2_CSFPB_CMD_RCGR		GCCE_CC_REG(GCCE_NCSFPB, 0x0004)
#define GCCE_N2_CSFPB_ALWAYS_ON_CBCR	GCCE_CC_REG(GCCE_NCSFPB, 0x000C)
#define GCCE_N2_CSFPB_CBCR		GCCE_CC_REG(GCCE_NCSFPB, 0x0010)

/* MDDR */
#define GCCE_N_MDDR			3
#define GCCE_S_MDDR			12
#define GCCE_N_GCCMS_BCR		GCCE_CC_REG(GCCE_N_MDDR, 0x0000)
#define GCCE_MDDR4_AHB_CBCR		GCCE_CC_REG(GCCE_N_MDDR, 0x0004)
#define GCCE_S_GCCMS_BCR		GCCE_CC_REG(GCCE_S_MDDR, 0x0000)
#define GCCE_MDDR5_AHB_CBCR		GCCE_CC_REG(GCCE_S_MDDR, 0x0004)

/* PCIE_SS */
#define GCCE_PCIE_SS_0				4
#define GCCE_PCIE_SS_1				5
#define GCCE_PCIE_SS_BCR(blk)			GCCE_CC_REG(blk, 0x0000)
#define GCCE_PCIE_SS_VBU_CMD_RCGR(blk)		GCCE_CC_REG(blk, 0x0004)
#define GCCE_PCIE_SS_SECSFPB_AHB_CBCR(blk)	GCCE_CC_REG(blk, 0x000C)
#define GCCE_PCIE_SS_VBU_CORE_CBCR(blk)		GCCE_CC_REG(blk, 0x0010)

/* QDSS */
#define GCCE_QDSS			10
#define GCCE_QDSS_BCR			GCCE_CC_REG(GCCE_QDSS, 0x0000)
#define GCCE_QDSS_ATB_CMD_RCGR		GCCE_CC_REG(GCCE_QDSS, 0x0004)
#define GCCE_AT_E1_CBCR			GCCE_CC_REG(GCCE_QDSS, 0x0010)
#define GCCE_AT_E2_CBCR			GCCE_CC_REG(GCCE_QDSS, 0x0014)
#define GCCE_AT_E3_CBCR			GCCE_CC_REG(GCCE_QDSS, 0x0018)
#define GCCE_HMSS_AT_E_CBCR		GCCE_CC_REG(GCCE_QDSS, 0x001C)
#define GCCE_AT_E5_CBCR			GCCE_CC_REG(GCCE_QDSS, 0x0020)
#define GCCE_AT_E7_CBCR			GCCE_CC_REG(GCCE_QDSS, 0x0024)
#define GCCE_AT_E9_CBCR			GCCE_CC_REG(GCCE_QDSS, 0x0028)

/* SCSFPB (S_CONF_SFPB) */
#define GCCE_SCSFPB			11
#define GCCE_S2_CSFPB_CMD_RCGR		GCCE_CC_REG(GCCE_SCSFPB, 0x0004)
#define GCCE_S2_CSFPB_ALWAYS_ON_CBCR	GCCE_CC_REG(GCCE_SCSFPB, 0x000C)
#define GCCE_S2_CSFPB_CBCR		GCCE_CC_REG(GCCE_SCSFPB, 0x0010)
#define GCCE_SECSFPB_AHB_CBCR		GCCE_CC_REG(GCCE_SCSFPB, 0x0014)
#define GCCE_SECSFPB			13
#define GCCE_SECSFPB_CMD_RCGR		GCCE_CC_REG(GCCE_SECSFPB, 0x0004)
#define GCCE_PSCLKGEN_CFG_AHB_CBCR	GCCE_CC_REG(GCCE_SECSFPB, 0x000C)
#define GCCE_SECSFPB_CBCR		GCCE_CC_REG(GCCE_SECSFPB, 0x0010)
#define GCCE_SECSFPB_ALWAYS_ON_CBCR	GCCE_CC_REG(GCCE_SECSFPB, 0x0014)

/* TSENS */
#define GCCE_TSENS5			14
#define GCCE_TSENS6			15
#define GCCE_TSENS7			16
#define GCCE_TSENS8			17

/* DEBUG */
#define GCCE_DEBUG			19
#define GCCE_DEBUG_CDIVR		GCCE_CC_REG(GCCE_DEBUG, 0x0010)
#define GCCE_DEBUG_CLK_CTL		GCCE_CC_REG(GCCE_DEBUG, 0x0014)
#define GCCE_PLLTEST_PAD_CFG		GCCE_CC_REG(GCCE_DEBUG, 0x0018)
#define GCCE_CLOCK_FRQ_MEASURE_CTL	GCCE_CC_REG(GCCE_DEBUG, 0x0020)
#define GCCE_CLOCK_FRQ_MEASURE_STATUS	GCCE_CC_REG(GCCE_DEBUG, 0x0024)
#define GCCE_TEST_BUS_CTL		GCCE_CC_REG(GCCE_DEBUG, 0x0028)

#endif /* _GCCE_QDF2400_H_INCLUDE__ */
