
obj-y :=

obj-$(CONFIG_ACPI_ENABLEOS) += apic_generate.o
obj-$(CONFIG_ACPI_ENABLEOS) += pptt_generate.o
obj-y += helper.o
obj-y += launch.o
obj-$(CONFIG_ACPI_ENABLEOS) += memmap_generate.o
obj-$(CONFIG_ACPI_ENABLEOS) += kernel_launch.o
