
obj-y :=

ccflags-y += -DHARVEST -DCONFIG_DDR

obj-y += mddr_info.o
obj-y += mddr_init.o
obj-y += mddr_mc_init.o
obj-y += mddr_mc_timing.o
obj-y += mddr_phy_init.o
obj-y += mddr_phy_loader.o
obj-y += mddr_phy_train.o
obj-y += mddr_power.o
obj-y += mddr_si.o
obj-y += spd.o
obj-y += spd_simm.o
obj-y += spd_smbus.o
obj-y += spd_smbus_impl.o

obj-y += ddr_driver.o
obj-y += ddrfw.o
obj-y += ddr_reg_logging.o
obj-y += ddrsi.o
obj-y += ddr_smbus_wrapper.o
obj-y += ddr_target_lib.o
obj-y += ddr_util_wrapper.o
obj-y += default_variables.o
obj-y += shared_variables.o
obj-y += XBLSharedVar.o
obj-y += XBLUtil.o
