obj-y :=

obj-y += ./sensor/
obj-y += ./control/
obj-y += ./frame_check/
obj-y += ./mcfe/
obj-y += ./output_formatter/
obj-y += ./ae_balanced/
obj-y += ./awb_mesh_NBP/
obj-y += ./cac/
obj-y += ./cmos/
obj-y += ./color_matrix/
obj-y += ./crop/
obj-y += ./decompander/
obj-y += ./defect_pixel/
obj-y += ./demosaic/
obj-y += ./histogram/
obj-y += ./iridix8/
obj-y += ./mesh_shading/
obj-y += ./ml_bist/
obj-y += ./noise_profile/
obj-y += ./noise_reduction/
obj-y += ./radial_shading/
obj-y += ./raw_fe/
obj-y += ./sharpening/

