//----------------------------------------------------------------------------
//   The confidential and proprietary information contained in this file may
//   only be used by a person authorised under and to the extent permitted
//   by a subsisting licensing agreement from ARM Limited or its affiliates.
//
//          (C) COPYRIGHT [2019] ARM Limited or its affiliates.
//              ALL RIGHTS RESERVED
//
//   This entire notice must be reproduced on all copies of this file
//   and copies of this file may only be made by a person if such person is
//   permitted to do so under the terms of a subsisting license agreement
//   from ARM Limited or its affiliates.
//----------------------------------------------------------------------------

#if !defined( __DUMMY_SENSOR_H__ )
#define __DUMMY_SENSOR_H__


/*-----------------------------------------------------------------------------
Generated by Sensor Sequence compiler(seq_compile_source.py) - do not edit
-----------------------------------------------------------------------------*/

#include "sensor_init.h"
static const sensor_reg_t seq_table[] = {
    //start_idx 0, size 4
    //group 0 seq1
    {0xFFFF, 20}, // wait command - address is 0xFFFF
    {0xFFFF, 0},  // wait command - address is 0xFFFF
    {0xaa56, 0xdead},
    {0xaa58, 0xbeef},
    {0x0000, 0x0000}, // stop sequence - address is 0x0000
                      //start_idx 4, size 6
                      //group 1 seq1plus
    {0xFFFF, 20},     // wait command - address is 0xFFFF
    {0xFFFF, 0},      // wait command - address is 0xFFFF
    {0xaa56, 0xdead},
    {0xaa58, 0xbeef},

    {0xaa0c, 0xdead},
    {0xaa30, 0xbeef},
    {0x0000, 0x0000}, // stop sequence - address is 0x0000

};


#define SENSOR_DUMMY_SEQUENCE_DEFAULT seq_table
#define SENSOR_DUMMY_SEQUENCE_DEFAULT_SEQ1 0
#define SENSOR_DUMMY_SEQUENCE_DEFAULT_SEQ1PLUS 5

#endif /* __DUMMY_SENSOR_H__ */
