obj-$(CONFIG_USB_DWC2_DEVICE) += dwc2_udc_otg.o
obj-$(CONFIG_USB_DWC2_DEVICE) += dwc2_udc_otg_phy.o
obj-$(CONFIG_USB_DWC3_GADGET) += dwc3_gadget.o core.o ep0.o udc-core.o

obj-y += composite.o config.o epautoconf.o usbstring.o
obj-y += serial/
obj-y += udc_cmd.o