//----------------------------------------------------------------------------
//   The confidential and proprietary information contained in this file may
//   only be used by a person authorised under and to the extent permitted
//   by a subsisting licensing agreement from ARM Limited or its affiliates.
//
//          (C) COPYRIGHT [2019] ARM Limited or its affiliates.
//              ALL RIGHTS RESERVED
//
//   This entire notice must be reproduced on all copies of this file
//   and copies of this file may only be made by a person if such person is
//   permitted to do so under the terms of a subsisting license agreement
//   from ARM Limited or its affiliates.
//----------------------------------------------------------------------------

// File generated by gen_global_settings.py
#ifndef __ACAMERA_SETTINGS_H__
#define __ACAMERA_SETTINGS_H__

#include "sensor_api.h"

typedef struct _acamera_settings {
    // Sensor related setting for the context
    char *sensor_name; // Sensor name string

    void ( *sensor_init )( void **priv_ptr,
                           uint8_t location,
                           sensor_control_t *ctrl,
                           const sensor_options_t *const options ); // Function ptr to initialize sensor

    sensor_options_t sensor_options; // Sensor options.

    // Context calibration / register settings
    int32_t ( *get_calibrations )( uint32_t wdr_mode, void *param ); // Function ptr to get calibration.

    // Other configurations
    int32_t isp_base; // ISP context CDMA offset from memory start address
} acamera_settings;


#endif //__ACAMERA_SETTINGS_H__
