
obj-y :=

obj-y += pdu.o 
obj-y += smmu_setup.o
obj-y += SmxaccKeygenTest_smmu.o
obj-y += VVDRV_qsmmuv3_CD.o
obj-y += VVDRV_qsmmuv3_common.o
obj-y += VVDRV_qsmmuv3_program.o
obj-y += VVDRV_qsmmuv3_STE.o
obj-y += VVDRV_qsmmuv3_TT.o
obj-y += VVDRV_qsmmuv3_VMTE.o
