
obj-y :=

obj-$(CONFIG_HDTS_SATA) += sata_init.o
obj-$(CONFIG_HDTS_SATA) += sata_rw.o
obj-$(CONFIG_HDTS_SATA) += sata_lb.o
obj-$(CONFIG_HDTS_SATA) += sata_default.o
obj-$(CONFIG_HDTS_SATA) += sata_intr.o

obj-$(CONFIG_PWRSOC_SATA) += sata_init.o

