#ifndef _TARGET_CUST_H
#define _TARGET_CUST_H

/*===========================================================================

                                Target_cust
                                Header File

GENERAL DESCRIPTION
  This header file contains target specific declarations and definitions

INITIALIZATION AND SEQUENCING REQUIREMENTS
  None

             Copyright (c) 2017 Qualcomm Datacenter Technologies, Inc.
                            All Rights Reserved.
            Confidential and Proprietary - Qualcomm Datacenter Technologies, Inc.

             Copyright (c) 2014-2016 Qualcomm Technologies, Inc.
                            All Rights Reserved.
            Confidential and Proprietary - Qualcomm Technologies, Inc.

============================================================================*/

/*===========================================================================

                           INCLUDE FILES

===========================================================================*/

/*===========================================================================
              DEFINES FOR TARGET (equivalent to <target>.builds src)
===========================================================================*/


/*===========================================================================
                      DEFINES FOR 2400 MEMORY MAP
===========================================================================*/
#define   SIZE_1KB  0x00000400
#define   SIZE_4KB  0x00001000
#define   SIZE_8KB  0x00002000
#define  SIZE_10KB  0x00002800
#define  SIZE_12KB  0x00003000
#define  SIZE_16KB  0x00004000
#define  SIZE_20KB  0x00005000
#define  SIZE_24KB  0x00006000
#define  SIZE_28KB  0x00007000
#define  SIZE_32KB  0x00008000
#define  SIZE_36KB  0x00009000
#define  SIZE_40KB  0x0000A000
#define  SIZE_48KB  0x0000C000
#define  SIZE_52KB  0x0000D000
#define  SIZE_56KB  0x0000E000
#define  SIZE_60KB  0x0000F000
#define  SIZE_64KB  0x00010000
#define  SIZE_68KB  0x00011000
#define  SIZE_72KB  0x00012000
#define  SIZE_76KB  0x00013000
#define  SIZE_80KB  0x00014000
#define  SIZE_84KB  0x00015000
#define  SIZE_88KB  0x00016000
#define  SIZE_92KB  0x00017000
#define  SIZE_96KB  0x00018000
#define SIZE_100KB  0x00019000
#define SIZE_128KB  0x00020000
#define SIZE_144KB  0x00024000
#define SIZE_192KB  0x00030000
#define SIZE_196KB  0x00031000
#define SIZE_216KB  0x00036000
#define SIZE_224KB  0x00038000
#define SIZE_228KB  0x00039000
#define SIZE_232KB  0x0003A000
#define SIZE_236KB  0x0003B000
#define SIZE_240KB  0x0003C000
#define SIZE_244KB  0x0003D000
#define SIZE_248KB  0x0003E000
#define SIZE_252KB  0x0003F000
#define SIZE_256KB  0x00040000
#define SIZE_280KB  0x00046000
#define SIZE_284KB  0x00047000
#define SIZE_288KB  0x00048000
#define SIZE_292KB  0x00049000
#define SIZE_296KB  0x0004A000
#define SIZE_378KB  0x0005E800
#define SIZE_382KB  0x000F5800
#define SIZE_400KB  0x00064000
#define SIZE_424KB  0x0006A000
#define SIZE_448KB  0x00070000
#define SIZE_512KB  0x00080000
#define SIZE_540KB  0x00088000
#define SIZE_768KB  0x000C0000
#define   SIZE_1MB  0x00100000
#define   SIZE_2MB  0x00200000
#define   SIZE_8MB  0x00800000
#define  SIZE_17MB  0x01100000
#define SIZE_512MB  0x20000000
#define   SIZE_1GB  0x40000000
#define   SIZE_2GB  0x80000000

#define SCL_IMC_IMEM_BASE 0xFF6F800000
#define SCL_IMC_IMEM_SIZE (SIZE_1MB+SIZE_512KB)
#define SCL_SYS_IMEM_BASE 0xFF70000000
#define SCL_SYS_IMEM_SIZE SIZE_256KB

#define SCL_SBL1_TOTAL_SIZE SIZE_400KB
#define SCL_SBL1_IMAGE_BASE (SCL_IMC_IMEM_BASE + SCL_IMC_TOTAL_SIZE)
#define SCL_SBL1_IMAGE_SIZE (SCL_IMC_IMEM_SIZE - SCL_IMC_TOTAL_SIZE)

#define SCL_SBL1_CODE_BASE SCL_SBL1_IMAGE_BASE
#define SCL_SBL1_CODE_SIZE SIZE_256KB

#define SCL_DEVICEPROG_CODE_SIZE SIZE_256KB

#define SCL_SBL1_VECTOR_BASE SCL_SBL1_CODE_BASE
#define SCL_SBL1_VECTOR_SIZE 0x00000020

#define SCL_SBL1_STACK_BASE (SCL_SBL1_CODE_BASE + SCL_SBL1_CODE_SIZE)
#define SCL_SBL1_STACK_SIZE SIZE_12KB
//Base address of stack is higher end-address of stack region
#define SBL1_STACK_BASE (SCL_SBL1_STACK_BASE + SCL_SBL1_STACK_SIZE)

#define SCL_SBL1_DATA_BASE (SCL_SBL1_STACK_BASE + SCL_SBL1_STACK_SIZE)
#define SCL_SBL1_DATA_SIZE SIZE_20KB
#define SCL_SBL1_DATA_ZI_BASE (SCL_SBL1_DATA_BASE + SCL_SBL1_DATA_SIZE)
#define SCL_SBL1_DATA_ZI_SIZE SIZE_96KB

#define SCL_SBL1_PAGE_TABLE_BASE (SCL_SBL1_DATA_ZI_BASE + SCL_SBL1_DATA_ZI_SIZE)
#define SCL_SBL1_PAGE_TABLE_SIZE SIZE_72KB

#define SCL_DEVICEPROG_DATA_SIZE SIZE_24KB
#define SCL_DEVICEPROG_DATA_ZI_SIZE SIZE_52KB

#define SCL_SYSTEM_IMEM_BASE SCL_SYS_IMEM_BASE
#define SCL_SYSTEM_IMEM_SIZE SIZE_128KB

#define SCL_DDR_PHY_FW_BASE (SCL_IMC_IMEM_BASE + SCL_IMC_IMEM_SIZE - SIZE_512KB)
#define SCL_DDR_PHY_FW_SIZE SIZE_252KB

#define SCL_DDR_PHY_SI_BASE (SCL_DDR_PHY_FW_BASE + SCL_DDR_PHY_FW_SIZE)
#define SCL_DDR_PHY_SI_SIZE SIZE_4KB

#define SCL_SINGLE_INSTANCE_ROM_BASE (SCL_DDR_PHY_SI_BASE + SCL_DDR_PHY_SI_SIZE)
#define SCL_SINGLE_INSTANCE_ROM_SIZE SIZE_196KB

#define SCL_SINGLE_INSTANCE_DATA_BASE (SCL_SINGLE_INSTANCE_ROM_BASE + SCL_SINGLE_INSTANCE_ROM_SIZE)
#define SCL_SINGLE_INSTANCE_DATA_SIZE SIZE_60KB

#define SCL_SYSTEM_DEBUG_ROM_BASE (SCL_SYSTEM_IMEM_BASE + SIZE_64KB)
#define SCL_SYSTEM_DEBUG_ROM_SIZE SIZE_32KB

#define SCL_SYSTEM_DEBUG_DATA_BASE (SCL_SYSTEM_DEBUG_ROM_BASE + SCL_SYSTEM_DEBUG_ROM_SIZE)
#define SCL_SYSTEM_DEBUG_DATA_SIZE SIZE_12KB

#define DEBUG_TABLE_BASE (SCL_SYSTEM_DEBUG_DATA_BASE + SCL_SYSTEM_DEBUG_DATA_SIZE)
#define DEBUG_TABLE_REGION_OFFSET  SIZE_1KB
#define DEBUG_TABLE_REGION_SIZE    SIZE_8KB
#define DEBUG_ENTRY_REGION_OFFSET  (DEBUG_TABLE_REGION_OFFSET + DEBUG_TABLE_REGION_SIZE)
#define DEBUG_ENTRY_REGION_SIZE    SIZE_8KB
#define DEBUG_BUFFER_REGION_OFFSET (DEBUG_ENTRY_REGION_OFFSET + DEBUG_ENTRY_REGION_SIZE)
#define DEBUG_TABLE_SIZE (DEBUG_TABLE_REGION_OFFSET + DEBUG_TABLE_REGION_SIZE + DEBUG_ENTRY_REGION_SIZE)
#define DEBUG_DDR_DUMP_SIZE SIZE_512MB
#define DEBUG_APC_STATUS_BUFFER_SIZE (0x800 * 23)
#define DEBUG_CPU_CONTEXT_BUFFER_SIZE (0x200 * (BOOT_MAX_NUM_CORES + 1))
#define DEBUG_BUFFER_REGION_SIZE   (SCL_SYS_IMEM_SIZE + SCL_IMC_IMEM_SIZE + DEBUG_DDR_DUMP_SIZE + DEBUG_APC_STATUS_BUFFER_SIZE + DEBUG_CPU_CONTEXT_BUFFER_SIZE + 0x200)
#define DEBUG_REGION_SIZE (DEBUG_TABLE_SIZE + DEBUG_BUFFER_REGION_SIZE)

#define SCL_DEVICEPROG_ZI_BASE (SCL_SYSTEM_IMEM_BASE + SCL_SYSTEM_IMEM_SIZE)
#define SCL_DEVICEPROG_ZI_SIZE SIZE_100KB
#define SCL_DEVICEPROG_PAGE_TABLE_BASE SCL_SBL1_DATA_ZI_BASE
#define SCL_DEVICEPROG_PAGE_TABLE_SIZE SIZE_64KB

#define BERT_RECORD_SIZE SIZE_36KB
#define BERT_RECORD_BASE (SCL_SYSTEM_IMEM_BASE + 0x00020000)
#define BERT_COOKIE_SIZE 8
#define BERT_COOKIE_BASE (BERT_RECORD_BASE + BERT_RECORD_SIZE - BERT_COOKIE_SIZE)

#define SCL_PMIC_CONFIG_BUF_BASE (BERT_RECORD_BASE + BERT_RECORD_SIZE)
#define SCL_PMIC_CONFIG_BUF_SIZE SIZE_24KB

#define SCL_FREQ_PLAN_BUF_BASE   (SCL_PMIC_CONFIG_BUF_BASE + SCL_PMIC_CONFIG_BUF_SIZE)
#define SCL_FREQ_PLAN_BUF_SIZE   SIZE_8KB

#define APPSBL_LOG_SIZE SIZE_4KB
#define APPSBL_LOG_BASE (SCL_SYS_IMEM_BASE + 0x00033000)

#define SHARED_IMEM_SIZE SIZE_4KB
#define SHARED_IMEM_BASE (SCL_SYS_IMEM_BASE + 0x00034000)
#define SHARED_IMEM_BOOT_BASE SHARED_IMEM_BASE
#define SHARED_IMEM_BOOT_SIZE 200
#define SHARED_IMEM_USB_BASE (SHARED_IMEM_BOOT_BASE + SHARED_IMEM_BOOT_SIZE)
#define SHARED_IMEM_USB_SIZE 200
#define SHARED_IMEM_BOOT_CDT_BASE (SHARED_IMEM_USB_BASE + SHARED_IMEM_USB_SIZE)
#define SHARED_IMEM_BOOT_CDT_SIZE 0x0000400
#define SHARED_IMEM_DDR_BASE (SHARED_IMEM_BOOT_CDT_BASE + SHARED_IMEM_BOOT_CDT_SIZE)
#define SHARED_IMEM_DDR_SIZE 200
#define SHARED_IMEM_HLOS_BASE (SHARED_IMEM_DDR_BASE + SHARED_IMEM_DDR_SIZE)
#define SHARED_IMEM_HLOS_SIZE 200
#define SHARED_IMEM_RPM_BASE (SHARED_IMEM_HLOS_BASE + SHARED_IMEM_HLOS_SIZE)
#define SHARED_IMEM_RPM_SIZE 8
#define SHARED_IMEM_QDSS_BASE (SHARED_IMEM_RPM_BASE + SHARED_IMEM_RPM_SIZE)
#define SHARED_IMEM_QDSS_SIZE 12
#define SHARED_IMEM_SECUREMSM_BASE (SHARED_IMEM_QDSS_BASE + SHARED_IMEM_QDSS_SIZE)
#define SHARED_IMEM_SECUREMSM_SIZE 512
#define SHARED_IMEM_PERIPHERAL_DEBUG_BASE (SHARED_IMEM_SECUREMSM_BASE + SHARED_IMEM_SECUREMSM_SIZE)
#define SHARED_IMEM_PERIPHERAL_DEBUG_SIZE 24
#define SHARED_IMEM_PIL_BASE (SHARED_IMEM_PERIPHERAL_DEBUG_BASE + SHARED_IMEM_PERIPHERAL_DEBUG_SIZE)
#define SHARED_IMEM_PIL_SIZE 200
#define SHARED_IMEM_TZ_BASE (SHARED_IMEM_PIL_BASE + SHARED_IMEM_PIL_SIZE)
#define SHARED_IMEM_TZ_SIZE 128
#define SHARED_IMEM_OEM_BASE (SHARED_IMEM_TZ_BASE + SHARED_IMEM_TZ_SIZE)
#define SHARED_IMEM_OEM_SIZE 100
#define SHARED_IMEM_SDI_BASE (SHARED_IMEM_OEM_BASE + SHARED_IMEM_OEM_SIZE)
#define SHARED_IMEM_SDI_SIZE 32
#define SHARED_IMEM_RAMDUMP_BASE (SHARED_IMEM_SDI_BASE + SHARED_IMEM_SDI_SIZE)
#define SHARED_IMEM_RAMDUMP_SIZE 4
#define SHARED_IMEM_UNUSED_SPACE_BASE (SHARED_IMEM_RAMDUMP_BASE + SHARED_IMEM_RAMDUMP_SIZE)
#define SHARED_IMEM_UNUSED_SPACE_SIZE 1152
#define SHARED_IMEM_BOOTROM_BASE (SHARED_IMEM_UNUSED_SPACE_BASE + SHARED_IMEM_UNUSED_SPACE_SIZE)
#define SHARED_IMEM_BOOTROM_SIZE 100


#define SCL_DEFAULT_VARIABLES_TEMP_BUF_BASE (SCL_IMC_IMEM_BASE)
#define SCL_DEFAULT_VARIABLES_TEMP_BUF_SIZE SIZE_8KB

#define SCL_SHARED_VARIABLES_TEMP_BUF_BASE (SCL_DEFAULT_VARIABLES_TEMP_BUF_BASE + SCL_DEFAULT_VARIABLES_TEMP_BUF_SIZE)
#define SCL_SHARED_VARIABLES_TEMP_BUF_SIZE SIZE_8KB

#define SCL_HOB_LIST_TEMP_BUF_BASE (SCL_SHARED_VARIABLES_TEMP_BUF_BASE + SCL_SHARED_VARIABLES_TEMP_BUF_SIZE)
#define SCL_HOB_LIST_TEMP_BUF_SIZE SIZE_8KB

#define SCL_DEFAULT_HOB_BASE (SCL_HOB_LIST_TEMP_BUF_BASE + SCL_HOB_LIST_TEMP_BUF_SIZE)
#define SCL_DEFAULT_HOB_SIZE SIZE_8KB

#define SCL_SPD_BUFFER_TEMP_BASE (SCL_DEFAULT_HOB_BASE + SCL_DEFAULT_HOB_SIZE)
#define SCL_SPD_BUFFER_TEMP_SIZE SIZE_8KB

#define HASH_SEGMENT_TEMP_BASE (SCL_SPD_BUFFER_TEMP_BASE + SCL_SPD_BUFFER_TEMP_SIZE)
#define HASH_SEGMENT_SIZE SIZE_40KB

#define SCL_DDR_MARGINING_RESULT_BASE (HASH_SEGMENT_TEMP_BASE + HASH_SEGMENT_SIZE)
#define SCL_DDR_MARGINING_RESULT_SIZE SIZE_92KB

#define DDR_MEM_BASE 0x0000000000000000
#define DDR_MEM_SIZE SIZE_2GB

/* SBL's DDR section is shared by Loader DDR Data */
#define SCL_SBL1_DDR_BASE (DDR_MEM_BASE + 0x00200000)
#define SCL_SBL1_DDR_SIZE 0x00200000

/* Loader HOB List.  Used to pass boot information to Core. */
#define SCL_XBL_LOADER_HOB_LIST_BASE (SCL_SBL1_DDR_BASE)
#define SCL_XBL_LOADER_HOB_LIST_SIZE SIZE_24KB

/* Loader Default Variable Data.  Used to pass shared variables to Core. */
#define SCL_XBL_LOADER_DEFAULT_VARIABLES_BASE (SCL_XBL_LOADER_HOB_LIST_BASE + SCL_XBL_LOADER_HOB_LIST_SIZE)
#define SCL_XBL_LOADER_DEFAULT_VARIABLES_SIZE SIZE_8KB

/* Loader Shared Variable Data.  Used to pass shared variables to Core. */
#define SCL_XBL_LOADER_SHARED_VARIABLES_BASE (SCL_XBL_LOADER_DEFAULT_VARIABLES_BASE + SCL_XBL_LOADER_DEFAULT_VARIABLES_SIZE)
#define SCL_XBL_LOADER_SHARED_VARIABLES_SIZE SIZE_8KB

/* DDR SPD Data.  Used to pass SPD Config to Core. */
#define SCL_XBL_LOADER_SPD_BUFFER_BASE (SCL_XBL_LOADER_SHARED_VARIABLES_BASE + SCL_XBL_LOADER_SHARED_VARIABLES_SIZE)
#define SCL_XBL_LOADER_SPD_BUFFER_SIZE SIZE_8KB

/* Hash Segment Location in DDR */
#define HASH_SEGMENT_BASE (SCL_XBL_LOADER_SPD_BUFFER_BASE + SCL_XBL_LOADER_SPD_BUFFER_SIZE)

/* Loadable ACPI Tables */
#define SCL_ACPI_BASE (DDR_MEM_BASE + 0x03000000)
#define SCL_ACPI_SIZE SIZE_540KB

/* SMEM */
#define SCL_SHARED_RAM_BASE (DDR_MEM_BASE + 0x00400000)
#define SCL_SHARED_RAM_SIZE SIZE_2MB

/* Loaded Images */
#define SCL_IMC_CODE_BASE SCL_IMC_IMEM_BASE
#define SCL_IMC_TOTAL_SIZE SIZE_256KB
#define SCL_XBL_CORE_CODE_BASE (DDR_MEM_BASE + 0x02800000)
#define SCL_XBL_CORE_TOTAL_SIZE SIZE_8MB
#define SCL_MM_CODE_BASE (DDR_MEM_BASE + 0x1BC00000)
#define SCL_MM_TOTAL_SIZE SIZE_512KB
#define SCL_TFW_CODE_BASE (DDR_MEM_BASE + 0x10000000)
#define SCL_TFW_TOTAL_SIZE SIZE_8MB
#define SCL_TPM_CODE_BASE (SCL_TFW_CODE_BASE + 0x00700000)
#define SCL_TPM_TOTAL_SIZE SIZE_1MB

#define SCL_SBL1_BOOT_LOG_META_INFO_SIZE 64
#define SCL_SBL1_BOOT_LOG_BUF_SIZE 3520
#define PBL_APPS_ROM_BASE 0x00100000
#define PBL_APPS_ROM_SIZE SIZE_144KB
#define SBL1_DEBUG_COOKIE_ADDR (SHARED_IMEM_PERIPHERAL_DEBUG_BASE + 0x10)
#define SBL1_DEBUG_COOKIE_VAL 0x53444247
#define SCL_DDR_TRAINING_DATA_BUF_SIZE 2048
#define SCL_IRAM_BASE SCL_IMC_IMEM_BASE
#define SCL_IRAM_SIZE SCL_IMC_IMEM_SIZE
#define IMAGE_KEY_EMMCBLD_IMG_DEST_ADDR SCL_SBL1_CODE_BASE+80
#define IMAGE_KEY_DEVICEPROGRAMMER_IMG_DEST_ADDR SCL_SBL1_CODE_BASE+80

/* Number of cores, clusters and L3 blocks this target supports */
#define BOOT_MAX_NUM_CORES       48
#define BOOT_MAX_NUM_CLUSTERS    24
#define BOOT_MAX_NUM_L3_BLOCKS   12

/* Number of dies this target supports */
#define BOOT_MAX_NUM_DIES        1

/* Supported CDT Size */
#define CONFIG_DATA_TABLE_SIZE   24

/* Allowed QoS IDs for FW */
#define QOS_ID_START             0xF0
#define QOS_ID_END               0xFF

/* Chip part number */
#define PART_NUM                 0x00000079

/* Supported PK_HASHs */
#define SUPPORTED_PK_HASH_NUM    4

/* SBL Command Max Length */
#define SUPPORTED_COMMAND_LEN    20

/*===========================================================================
                 Defines to support enhanced boot logging
============================================================================*/
#define BOOT_LOGGER_BOOT_CONFIG_FUSE_ADDRESS           HWIO_BOOT_CONFIG_ADDR
#define BOOT_LOGGER_JTAG_ID_FUSE_ADDRESS               HWIO_JTAG_ID_ADDR
#define BOOT_LOGGER_OEM_ID_FUSE_ADDRESS                HWIO_OEM_ID_ADDR
#define BOOT_LOGGER_SERIAL_NUM_FUSE_ADDRESS            HWIO_QFPROM_CORR_SERIAL_NUM_LSB_ADDR
#define BOOT_LOGGER_EXTENDED_CHIP_ID_FUSE_ADDRESS      HWIO_QFPROM_CORR_SERIAL_NUM_MSB_ADDR
#define BOOT_LOGGER_OEM_CONFIG_ROW_0_FUSE_ADDRESS      HWIO_QFPROM_CORR_OEM_CONFIG_ROW0_LSB_ADDR
#define BOOT_LOGGER_OEM_CONFIG_ROW_1_FUSE_ADDRESS      HWIO_QFPROM_CORR_OEM_CONFIG_ROW1_LSB_ADDR
#define BOOT_LOGGER_FEATURE_CONFIG_ROW_0_FUSE_ADDRESS  HWIO_QFPROM_CORR_FEAT_CONFIG_ROW0_LSB_ADDR
#define BOOT_LOGGER_FEATURE_CONFIG_ROW_1_FUSE_ADDRESS  HWIO_QFPROM_CORR_FEAT_CONFIG_ROW1_LSB_ADDR
#define BOOT_LOGGER_RTL_MAJOR_VERSION_ADDRESS          (HWIO_SPARE3_ADDR + 0x30)
#define BOOT_LOGGER_RTL_MINOR_VERSION_ADDRESS          (HWIO_SPARE3_ADDR + 0x34)


/*===========================================================================
                 Defines to support NODOC Registers
============================================================================*/
#define HWIO_QFPROM_CPU_CBF_FREQ_ADDR           0xFF0C706410
#define HWIO_QFPROM_CPU_CBF_FREQ_CBF_FBASE_BMSK 0xff000000
#define HWIO_QFPROM_CPU_CBF_FREQ_CBF_FBASE_SHFT 0x18
#define HWIO_QFPROM_CPU_CBF_FREQ_CPU_FBASE_BMSK 0xff0000
#define HWIO_QFPROM_CPU_CBF_FREQ_CPU_FBASE_SHFT 0x10
#define HWIO_QFPROM_CPU_CBF_FREQ_CBF_FMAX_BMSK  0xff00
#define HWIO_QFPROM_CPU_CBF_FREQ_CBF_FMAX_SHFT  0x8
#define HWIO_QFPROM_CPU_CBF_FREQ_CPU_FMAX_BMSK  0xff
#define HWIO_QFPROM_CPU_CBF_FREQ_CPU_FMAX_SHFT  0x0


/*===========================================================================
                 Defines to tell unsupported silicon revisions
============================================================================*/
#define BOOT_UNSUPPORTED_SILICON_VERSIONS              {0x00}


/*===========================================================================
                      FEATURE DEFINES USED ACROSS DRIVERS
===========================================================================*/

#define FEATURE_EFS_EFS2_ON_RMTS
#define DDR_XO_SPEED_IN_KHZ 20000
#undef  FEATURE_USE_PBL_SECBOOT_API

#endif  /* _TARGET_CUST_H */
