//----------------------------------------------------------------------------
//   The confidential and proprietary information contained in this file may
//   only be used by a person authorised under and to the extent permitted
//   by a subsisting licensing agreement from ARM Limited or its affiliates.
//
//          (C) COPYRIGHT [2019] ARM Limited or its affiliates.
//              ALL RIGHTS RESERVED
//
//   This entire notice must be reproduced on all copies of this file
//   and copies of this file may only be made by a person if such person is
//   permitted to do so under the terms of a subsisting license agreement
//   from ARM Limited or its affiliates.
//----------------------------------------------------------------------------

#include "context_params.h"
#include "isp_params.h"

// Map API command id to param id
#define COMMAND_TO_PARAM_MAP_MAX_ID 0x00000053

static uint32_t command_to_param_map[COMMAND_TO_PARAM_MAP_MAX_ID + 1] = {
    FW_REVISION_PARAM,                             // FW_REVISION
    CONTEXT_NUMBER_PARAM,                          // CONTEXT_NUMBER
    ACTIVE_CONTEXT_PARAM,                          // ACTIVE_CONTEXT
    SENSOR_SUPPORTED_PRESETS_PARAM,                // SENSOR_SUPPORTED_PRESETS
    SENSOR_PRESET_PARAM,                           // SENSOR_PRESET
    SENSOR_WDR_MODE_PARAM,                         // SENSOR_WDR_MODE
    SENSOR_STREAMING_PARAM,                        // SENSOR_STREAMING
    SENSOR_EXPOSURES_PARAM,                        // SENSOR_EXPOSURES
    SENSOR_FPS_PARAM,                              // SENSOR_FPS
    SENSOR_WIDTH_PARAM,                            // SENSOR_WIDTH
    SENSOR_HEIGHT_PARAM,                           // SENSOR_HEIGHT
    SYSTEM_LOGGER_LEVEL_PARAM,                     // SYSTEM_LOGGER_LEVEL
    SYSTEM_LOGGER_MASK_PARAM,                      // SYSTEM_LOGGER_MASK
    MCFE_USECASE_PARAM,                            // MCFE_USECASE
    BUFFER_DATA_TYPE_PARAM,                        // BUFFER_DATA_TYPE
    TEST_PATTERN_ENABLE_ID_PARAM,                  // TEST_PATTERN_ENABLE_ID
    TEST_PATTERN_MODE_ID_PARAM,                    // TEST_PATTERN_MODE_ID
    SYSTEM_FREEZE_FIRMWARE_PARAM,                  // SYSTEM_FREEZE_FIRMWARE
    SYSTEM_MANUAL_EXPOSURE_PARAM,                  // SYSTEM_MANUAL_EXPOSURE
    SYSTEM_MANUAL_MAX_INTEGRATION_TIME_PARAM,      // SYSTEM_MANUAL_MAX_INTEGRATION_TIME
    SYSTEM_MANUAL_EXPOSURE_RATIO_PARAM,            // SYSTEM_MANUAL_EXPOSURE_RATIO
    SYSTEM_MANUAL_INTEGRATION_TIME_PARAM,          // SYSTEM_MANUAL_INTEGRATION_TIME
    SYSTEM_MANUAL_SENSOR_ANALOG_GAIN_PARAM,        // SYSTEM_MANUAL_SENSOR_ANALOG_GAIN
    SYSTEM_MANUAL_SENSOR_DIGITAL_GAIN_PARAM,       // SYSTEM_MANUAL_SENSOR_DIGITAL_GAIN
    SYSTEM_MANUAL_ISP_DIGITAL_GAIN_PARAM,          // SYSTEM_MANUAL_ISP_DIGITAL_GAIN
    SYSTEM_MANUAL_DIRECTIONAL_SHARPENING_PARAM,    // SYSTEM_MANUAL_DIRECTIONAL_SHARPENING
    SYSTEM_MANUAL_UN_DIRECTIONAL_SHARPENING_PARAM, // SYSTEM_MANUAL_UN_DIRECTIONAL_SHARPENING
    SYSTEM_MANUAL_AWB_PARAM,                       // SYSTEM_MANUAL_AWB
    SYSTEM_ANTIFLICKER_ENABLE_PARAM,               // SYSTEM_ANTIFLICKER_ENABLE
    SYSTEM_MANUAL_SATURATION_PARAM,                // SYSTEM_MANUAL_SATURATION
    SYSTEM_EXPOSURE_PARAM,                         // SYSTEM_EXPOSURE
    SYSTEM_INTEGRATION_TIME_PRECISION_PARAM,       // SYSTEM_INTEGRATION_TIME_PRECISION
    SYSTEM_EXPOSURE_RATIO_PARAM,                   // SYSTEM_EXPOSURE_RATIO
    SYSTEM_MAX_EXPOSURE_RATIO_PARAM,               // SYSTEM_MAX_EXPOSURE_RATIO
    SYSTEM_INTEGRATION_TIME_PARAM,                 // SYSTEM_INTEGRATION_TIME
    SYSTEM_LONG_INTEGRATION_TIME_PARAM,            // SYSTEM_LONG_INTEGRATION_TIME
    SYSTEM_MIDDLE_INTEGRATION_TIME_PARAM,          // SYSTEM_MIDDLE_INTEGRATION_TIME
    SYSTEM_SHORT_INTEGRATION_TIME_PARAM,           // SYSTEM_SHORT_INTEGRATION_TIME
    SYSTEM_MAX_INTEGRATION_TIME_PARAM,             // SYSTEM_MAX_INTEGRATION_TIME
    SYSTEM_SENSOR_ANALOG_GAIN_PARAM,               // SYSTEM_SENSOR_ANALOG_GAIN
    SYSTEM_MAX_SENSOR_ANALOG_GAIN_PARAM,           // SYSTEM_MAX_SENSOR_ANALOG_GAIN
    SYSTEM_SENSOR_DIGITAL_GAIN_PARAM,              // SYSTEM_SENSOR_DIGITAL_GAIN
    SYSTEM_MAX_SENSOR_DIGITAL_GAIN_PARAM,          // SYSTEM_MAX_SENSOR_DIGITAL_GAIN
    SYSTEM_ISP_DIGITAL_GAIN_PARAM,                 // SYSTEM_ISP_DIGITAL_GAIN
    SYSTEM_MAX_ISP_DIGITAL_GAIN_PARAM,             // SYSTEM_MAX_ISP_DIGITAL_GAIN
    SYSTEM_DIRECTIONAL_SHARPENING_TARGET_PARAM,    // SYSTEM_DIRECTIONAL_SHARPENING_TARGET
    SYSTEM_UN_DIRECTIONAL_SHARPENING_TARGET_PARAM, // SYSTEM_UN_DIRECTIONAL_SHARPENING_TARGET
    SYSTEM_IRIDIX_STRENGTH_TARGET_PARAM,           // SYSTEM_IRIDIX_STRENGTH_TARGET
    SYSTEM_MAXIMUM_IRIDIX_STRENGTH_PARAM,          // SYSTEM_MAXIMUM_IRIDIX_STRENGTH
    SYSTEM_MINIMUM_IRIDIX_STRENGTH_PARAM,          // SYSTEM_MINIMUM_IRIDIX_STRENGTH
    SYSTEM_IRIDIX_DIGITAL_GAIN_PARAM,              // SYSTEM_IRIDIX_DIGITAL_GAIN
    SYSTEM_SINTER_THRESHOLD_TARGET_PARAM,          // SYSTEM_SINTER_THRESHOLD_TARGET
    SYSTEM_AWB_RED_GAIN_PARAM,                     // SYSTEM_AWB_RED_GAIN
    SYSTEM_AWB_BLUE_GAIN_PARAM,                    // SYSTEM_AWB_BLUE_GAIN
    SYSTEM_SATURATION_TARGET_PARAM,                // SYSTEM_SATURATION_TARGET
    SYSTEM_ANTI_FLICKER_FREQUENCY_PARAM,           // SYSTEM_ANTI_FLICKER_FREQUENCY
    IMAGE_CROP_ENABLE_ID_PARAM,                    // IMAGE_CROP_ENABLE_ID
    IMAGE_CROP_WIDTH_ID_PARAM,                     // IMAGE_CROP_WIDTH_ID
    IMAGE_CROP_HEIGHT_ID_PARAM,                    // IMAGE_CROP_HEIGHT_ID
    IMAGE_CROP_XOFFSET_ID_PARAM,                   // IMAGE_CROP_XOFFSET_ID
    IMAGE_CROP_YOFFSET_ID_PARAM,                   // IMAGE_CROP_YOFFSET_ID
    OUTPUT_AXI1_FORMAT_ID_PARAM,                   // OUTPUT_AXI1_FORMAT_ID
    OUTPUT_AXI2_FORMAT_ID_PARAM,                   // OUTPUT_AXI2_FORMAT_ID
    OUTPUT_AXI3_FORMAT_ID_PARAM,                   // OUTPUT_AXI3_FORMAT_ID
    OUTPUT_FORMAT_MANUAL_CFG_APPLY_ID_PARAM,       // OUTPUT_FORMAT_MANUAL_CFG_APPLY_ID
    OUTPUT_FORMAT_ID_PARAM,                        // OUTPUT_FORMAT_ID
    AE_ROI_ID_PARAM,                               // AE_ROI_ID
    AE_COMPENSATION_ID_PARAM,                      // AE_COMPENSATION_ID
    AWB_ROI_ID_PARAM,                              // AWB_ROI_ID
    REGISTERS_ADDRESS_ID_PARAM,                    // REGISTERS_ADDRESS_ID
    REGISTERS_SIZE_ID_PARAM,                       // REGISTERS_SIZE_ID
    REGISTERS_SOURCE_ID_PARAM,                     // REGISTERS_SOURCE_ID
    REGISTERS_VALUE_ID_PARAM,                      // REGISTERS_VALUE_ID
    STATUS_INFO_EXPOSURE_LOG2_ID_PARAM,            // STATUS_INFO_EXPOSURE_LOG2_ID
    STATUS_INFO_GAIN_ONES_ID_PARAM,                // STATUS_INFO_GAIN_ONES_ID
    STATUS_INFO_GAIN_LOG2_ID_PARAM,                // STATUS_INFO_GAIN_LOG2_ID
    STATUS_INFO_AWB_MIX_LIGHT_CONTRAST_PARAM,      // STATUS_INFO_AWB_MIX_LIGHT_CONTRAST
    ISP_MODULES_MANUAL_IRIDIX_PARAM,               // ISP_MODULES_MANUAL_IRIDIX
    ISP_MODULES_MANUAL_SINTER_PARAM,               // ISP_MODULES_MANUAL_SINTER
    ISP_MODULES_MANUAL_FRAME_STITCH_PARAM,         // ISP_MODULES_MANUAL_FRAME_STITCH
    ISP_MODULES_MANUAL_RAW_FRONTEND_PARAM,         // ISP_MODULES_MANUAL_RAW_FRONTEND
    ISP_MODULES_MANUAL_BLACK_LEVEL_PARAM,          // ISP_MODULES_MANUAL_BLACK_LEVEL
    ISP_MODULES_MANUAL_SHADING_PARAM,              // ISP_MODULES_MANUAL_SHADING
    ISP_MODULES_MANUAL_DEMOSAIC_PARAM              // ISP_MODULES_MANUAL_DEMOSAIC
};

// Translate command id to parameter id
uint32_t command_id_to_param_id( uint32_t command_id )
{
    if ( command_id > COMMAND_TO_PARAM_MAP_MAX_ID ) {
        return 0;
    } else {
        return command_to_param_map[command_id];
    }
}
