
obj-y :=

obj-y += emac_drv.o
obj-y += emac_ephy.o
obj-y += emac_ephy_drv_marvell_88e1111.o
obj-y += emac_ephy_drv_qca_ar8031.o
obj-y += emac_framework.o
obj-y += emac_phy_sgmii.o
obj-y += emac_platform.o
obj-y += emac_snp.o
