
obj-y:=
obj-y += rand.o
obj-y += string.o
obj-y += stdio.o
obj-y += strcpy.o
obj-y += strtoul.o
obj-y += strtoull.o
obj-y += vsnprintf.o
obj-y += byte_list.o

obj-$(CONFIG_CRC16_CCITT) += crc16.o
obj-y += fabsf.o
obj-y += strlcat.o
obj-y += strlcpy.o
