/*
*
* SPDX-License-Identifier: GPL-2.0
*
* Copyright (C) 2011-2019 ARM or its affiliates
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; version 2.
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
* You should have received a copy of the GNU General Public License along
* with this program; if not, write to the Free Software Foundation, Inc.,
* 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
*
*/

#ifndef __AR0231_DEMO_CONFIG_H__
#define __AR0231_DEMO_CONFIG_H__


// AR0231_DEMO.set
#define SENSOR_OUTPUT_BITS 12
#define SENSOR_DEV_ADDRESS 0x10
#define SENSOR_SAMPLE_MASK 3
#define SENSOR_ENDIAN_MASK 1
#define SENSOR_BUS_ADDR_SHIFT 0
#define RESOLUTION_CHANGE_ENABLED 1
#define PREVIEW_EXTRA_WIDTH 0
#define PREVIEW_EXTRA_HEIGHT 0
#define FULL_EXTRA_WIDTH 0
#define FULL_EXTRA_HEIGHT 0
#define SENSOR_IMAGE_WIDTH_PREVIEW 1920
#define SENSOR_IMAGE_HEIGHT_PREVIEW 1080
#define SENSOR_TOTAL_WIDTH_PREVIEW 1928
#define SENSOR_TOTAL_HEIGHT_PREVIEW 1208
#define SENSOR_MAX_INTEGRATION_TIME_PREVIEW ( SENSOR_TOTAL_WIDTH_PREVIEW - 14 )
#define SENSOR_IMAGE_WIDTH_FULL 1928
#define SENSOR_IMAGE_HEIGHT_FULL 1208
#define SENSOR_TOTAL_WIDTH 1928
#define SENSOR_TOTAL_HEIGHT 1208
#define SENSOR_MAX_INTEGRATION_TIME ( SENSOR_TOTAL_HEIGHT - 14 )
#define SENSOR_DAY_LIGHT_INTEGRATION_TIME_LIMIT 200
#define ISP_IMAGE_WIDTH SENSOR_IMAGE_WIDTH_PREVIEW
#define ISP_IMAGE_HEIGHT SENSOR_IMAGE_HEIGHT_PREVIEW
#define SENSOR_MIN_INTEGRATION_TIME 1
#define SENSOR_INTEGRATION_TIME_PRECISION 8
#define SENSOR_MAX_T1_BUFFER 76
#define SENSOR_MAX_T2_BUFFER 8
#define LOG2_SENSOR_AGAIN_MAXIMUM 3
#define LOG2_SENSOR_DGAIN_MAXIMUM 4
#define LOG2_SENSOR_WB_GAIN_MAXIMUM 0
#define LOG2_SENSOR_DGAIN_NATIVE_MAXIMUM 0
#define LOG2_SENSOR_WB_GAIN_NATIVE_MAXIMUM 4
#define SENSOR_INTEGRATION_TIME_APPLY_DELAY 2
#define SENSOR_ANALOG_GAIN_APPLY_DELAY ( SENSOR_INTEGRATION_TIME_APPLY_DELAY - 2 )
#define SENSOR_DIGITAL_GAIN_APPLY_DELAY 2
#define SENSOR_FRAME_STATUS 0x2008
#define SENSOR_FRAME_STATUS_PLL_LOCKED_BIT 3
#define SENSOR_REGADDR_CHIP_VERSION_REG 0x3000
#define SENSOR_REGADDR_X_ADDR_START 0x3004
#define SENSOR_REGADDR_X_ADDR_END 0x3008
#define SENSOR_REGADDR_Y_ADDR_START 0x3002
#define SENSOR_REGADDR_Y_ADDR_END 0x3006
#define SENSOR_REGADDR_LINE_LENGH_PCK 0x300C
#define SENSOR_REGADDR_FRAME_LENGTH_LINES 0x300A
#define SENSOR_REGADDR_REVISION_NUMBER 0x300E
#define SENSOR_REGADDR_RESET_REGISTER 0x301A
#define SENSOR_REGADDR_GROUPED_PARAMETER_HOLD 0x3022
#define SENSOR_REGADDR_VT_PIX_CLK_DIV 0x302A
#define SENSOR_REGADDR_VT_SYS_CLK_DIV 0x302C
#define SENSOR_REGADDR_PRE_PLL_CLK_DIV 0x302E
#define SENSOR_REGADDR_PLL_MULTIPLIER 0x3030
#define SENSOR_REGADDR_INTEGRATION_TIME 0x3012
#define SENSOR_REGADDR_INTEGRATION_TIME2 0x3212
#define SENSOR_REGADDR_INTEGRATION_TIME3 0x3216
#define SENSOR_REGADDR_INTEGRATION_TIME4 0x321A
#define SENSOR_REGADDR_DGAIN_R 0x305A
#define SENSOR_REGADDR_DGAIN_B 0x3058
#define SENSOR_REGADDR_DGAIN_G1 0x3056
#define SENSOR_REGADDR_DGAIN_G2 0x305C
#define SENSOR_REGADDR_POST_DLO_DGAIN_G1 0x3300
#define SENSOR_REGADDR_POST_DLO_DGAIN_B 0x3302
#define SENSOR_REGADDR_POST_DLO_DGAIN_R 0x3304
#define SENSOR_REGADDR_POST_DLO_DGAIN_G2 0x3306
#define SENSOR_REGADDR_GLOBAL_GAIN 0x305E
#define SENSOR_REGADDR_EXPOSURE_RATIO 0x3238
#define SENSOR_REGADDR_ANALOG_GAIN 0x3366
#define SENSOR_REGADDR_CONV_GAIN 0x3362
#define SENSOR_REGADDR_OPERATION_MODE_CTRL 0x3082
#define SENSOR_BOARD_MASTER_CLOCK 24000
// sensor_defaults.set
#define SENSOR_SEQUENCE_NAME default
#define SPI_CLOCK_DIV 40
#define SPI_CONTROL_MASK ( RX_NEG_MSK | ( CHAR_LEN_MSK & 32 ) | AUTO_SS_MSK | LSB_MSK )
#define SENSOR_BLACK_LEVEL_CORRECTION 0
#define SENSOR_SEQUENCE_FULL_RES_MAX_FPS 0
#define SENSOR_SEQUENCE_PREVIEW_RES_MAX_FPS 1
#define SENSOR_SEQUENCE_FULL_RES_HALF_FPS 2
#define SENSOR_SEQUENCE_PREVIEW_RES_HALF_FPS 3
#define SENSOR_EXP_NUMBER 1
#define SENSOR_BUS sbus_i2c
#define SENSOR_MAX_INTEGRATION_TIME_LIMIT SENSOR_MAX_INTEGRATION_TIME
#define SENSOR_MIN_INTEGRATION_TIME_NATIVE SENSOR_MIN_INTEGRATION_TIME
#define SENSOR_MAX_INTEGRATION_TIME_NATIVE SENSOR_MAX_INTEGRATION_TIME
#define SENSOR_AF_MOVE_DELAY 20
#endif
