/*
*
* SPDX-License-Identifier: GPL-2.0
*
* Copyright (C) 2011-2019 ARM or its affiliates
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; version 2.
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
* You should have received a copy of the GNU General Public License along
* with this program; if not, write to the Free Software Foundation, Inc.,
* 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
*
*/

#if !defined( __AR0231_SENSOR_H__ )
#define __AR0231_SENSOR_H__


/*-----------------------------------------------------------------------------
Generated by Sensor Sequence compiler(seq_compile_binary.py) - do not edit
-----------------------------------------------------------------------------*/

#define SENSOR_AR0231_SEQUENCE_DEFAULT_SIZE 5733
#define SENSOR_AR0231_SEQUENCE_DEFAULT_INIT_MIPI_1920X1080_15FPS 3
#define SENSOR_AR0231_SEQUENCE_DEFAULT_INIT_4LINE_1920X1080_30FPS 1
#define SENSOR_AR0231_SEQUENCE_DEFAULT_INIT_MIPI_NATIVE_WDR_3EXP 0
#define SENSOR_AR0231_SEQUENCE_DEFAULT_INIT_MIPI_NATIVE_WDR_3EXP_15FPS 2
#define SENSOR_AR0231_SEQUENCE_DEFAULT_INIT_NATIVE_4LINE_1928X1208 4
#define SENSOR_AR0231_SEQUENCE_DEFAULT_INIT_MIPI_DOL_4EXP 5
#define SENSOR_AR0231_SEQUENCE_DEFAULT_INIT_MIPI_DOL_3EXP 6
#define SENSOR_AR0231_SEQUENCE_DEFAULT_INIT_MIPI_DOL_2EXP 7

#endif /* __AR0231_SENSOR_H__ */
