obj-y :=

#obj-y += acamera_calibrations_dynamic_linear_dummy.o
#obj-y += acamera_calibrations_static_linear_dummy.o
#obj-y += acamera_get_calibrations_dummy.o

#obj-y += acamera_calibrations_dynamic_fs_lin_ar0231.o
#obj-y += acamera_calibrations_static_fs_lin_ar0231.o
obj-y += acamera_get_calibrations_ar0231.o
obj-y += acamera_calibrations_dynamic_linear_ar0231.o
obj-y += acamera_calibrations_static_linear_ar0231.o
