obj-y :=

obj-y += acamera.o
obj-y += acamera_command_api.o
obj-y += acamera_command_api_impl.o
obj-y += acamera_interrupts.o
obj-y += acamera_isp_ctx.o
obj-y += ./acamera_frame_streamer/
obj-y += ./calib_mgr/
obj-y += ./fsmgr/
