
obj-y :=

obj-$(CONFIG_PCIE_QCOM) += pcie_init.o
obj-$(CONFIG_PCIE_QCOM) += PcieI2cIo.o
obj-$(CONFIG_PCIE_QCOM) += DriveSlotPortExpander.o
obj-$(CONFIG_PCIE_QCOM) += PcieSlotPortExpander.o
obj-$(CONFIG_PCIE_QCOM) += pci.o