
obj-y :=

obj-$(CONFIG_TCMTEST) += tcmtest.o
obj-$(CONFIG_ASMPERCPU) += s_asmpercpu.o
obj-$(CONFIG_ASMPERCPU) += c_asmpercpu.o
obj-$(CONFIG_MEMRAND) += memrand.o
obj-$(CONFIG_SPINLOCK_TEST) += spinlock_test.o
