obj-y :=

obj-y += system_assert.o
obj-y += system_cache.o
obj-y += system_cma.o
obj-y += system_control.o
obj-y += system_i2c.o
obj-y += system_interrupts.o
obj-y += system_isp_io.o
obj-y += system_semaphore.o
obj-y += system_spinlock.o
obj-y += system_stdlib.o
obj-y += system_timer.o
obj-y += system_platform.o
