
obj-y :=

obj-y += crypto_ips_sha.o
obj-y += crypto_ips.o
obj-y += crypto_ips_aes.o
#obj-y += crypto_sw.o
obj-y += crypto_smx.o
obj-y += crypto_smx_sm3.o
obj-y += crypto_smx_sm4.o
obj-y += crypto_ips_general.o
obj-y += crypto_smx_general.o
