obj-y :=

obj-y += module_mcfe.o
obj-y += module_mcfe_hwif_common.o
obj-y += module_mcfe_service.o
obj-y += module_mcfe_service_buf.o
obj-y += module_mcfe_service_bufset.o
obj-y += module_mcfe_service_input.o
obj-y += module_mcfe_service_slot.o
obj-y += module_mcfe_usecase.o
obj-y += module_mcfe_usecase_manual.o
obj-y += module_mcfe_usecase_tdmf.o
obj-y += ./mcfe_r1/
