
asflags-y += -DDONT_USE_DC

obj-y :=
obj-y += memcmp.o
#obj-y += memcpy.o
obj-y += memmove.o
obj-y += memset.o
obj-y += strcmp.o
obj-y += strlen.o
obj-y += strncmp.o
obj-y += strnlen.o
obj-y += cache_helpers.o
